# Generated by Django 4.0.10 on 2023-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='loc',
            field=models.CharField(choices=[('Birbhum', 'Birbhum'), ('General', 'General'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Bankura', 'Bankura'), ('Jhargram', 'Jhargram'), ('Purlia', 'Purlia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='district',
            field=models.CharField(choices=[('Birbhum', 'Birbhum'), ('General', 'General'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Bankura', 'Bankura'), ('Jhargram', 'Jhargram'), ('Purlia', 'Purlia')], max_length=30),
        ),
    ]
