# Generated by Django 4.0.10 on 2023-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmksapi', '0006_alter_data_loc_alter_message_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='loc',
            field=models.CharField(choices=[('Jhargram', 'Jhargram'), ('General', 'General'), ('Purlia', 'Purlia'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Birbhum', 'Birbhum'), ('Bankura', 'Bankura')], max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='district',
            field=models.CharField(choices=[('Jhargram', 'Jhargram'), ('General', 'General'), ('Purlia', 'Purlia'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Birbhum', 'Birbhum'), ('Bankura', 'Bankura')], max_length=30),
        ),
    ]
